### ISSUE TITLE
Support PS-242.*

### ISSUE THREAD

**Issue by reedy** [ThexXTURBOXx/intellij-diff-plugin#5]
```
Plugin 'Diff / Patch File Support' (version '2.1.13') is not compatible with the current version of the IDE, because it requires build 241.* or older but the current build is PS-242.10180.24
```

Thanks!

**Comment by ThexXTURBOXx** [comment]
Good catch! Thank you very much for reminding me to update this plugin. Will do so tomorrow - sorry for the delay!

**Comment by ThexXTURBOXx** [comment]
It's not "tomorrow", but I had some free time now - so why not do it then?
Fixed in https://github.com/ThexXTURBOXx/intellij-diff-plugin/commit/92f1e05824e14ac1cc963bcf00b697a20b0b3dd9
Uploaded to marketplace already. After review, it will be avilable for download
